#!/usr/bin/env bash
# Bump the pinned clawpatrol release in overlays/clawpatrol.nix.
#
# Usage: ./update-clawpatrol.sh <version>      e.g. ./update-clawpatrol.sh 0.5.3
#
# Pulls the release's SHA256SUMS asset (the file-content hashes of each
# prebuilt binary, which is exactly what fetchurl verifies) and rewrites the
# `version` line plus the generated `asset` block in overlays/clawpatrol.nix.
# Requires: gh, nix, awk.
set -euo pipefail

ver="${1:?usage: $0 <version>  (e.g. 0.5.3)}"
ver="${ver#v}" # accept both 0.5.3 and v0.5.3
repo="denoland/clawpatrol"
overlay="$(dirname "$0")/overlays/clawpatrol.nix"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
gh release download "v$ver" -R "$repo" -p SHA256SUMS -D "$tmp"

to_sri() { nix hash convert --hash-algo sha256 --to sri "$1"; }

declare -A sri
while read -r hex name; do
  case "$name" in
    clawpatrol-linux-amd64)  sri[x86_64-linux]=$(to_sri "$hex") ;;
    clawpatrol-linux-arm64)  sri[aarch64-linux]=$(to_sri "$hex") ;;
    clawpatrol-darwin-amd64) sri[x86_64-darwin]=$(to_sri "$hex") ;;
    clawpatrol-darwin-arm64) sri[aarch64-darwin]=$(to_sri "$hex") ;;
  esac
done < "$tmp/SHA256SUMS"

for s in x86_64-linux aarch64-linux x86_64-darwin aarch64-darwin; do
  [ -n "${sri[$s]:-}" ] || { echo "missing hash for $s in SHA256SUMS" >&2; exit 1; }
done

block=$(cat <<EOF
  asset = {
    "x86_64-linux"   = { name = "clawpatrol-linux-amd64";  hash = "${sri[x86_64-linux]}"; };
    "aarch64-linux"  = { name = "clawpatrol-linux-arm64";  hash = "${sri[aarch64-linux]}"; };
    "x86_64-darwin"  = { name = "clawpatrol-darwin-amd64"; hash = "${sri[x86_64-darwin]}"; };
    "aarch64-darwin" = { name = "clawpatrol-darwin-arm64"; hash = "${sri[aarch64-darwin]}"; };
  }.\${system} or (throw "clawpatrol: unsupported system \${system}");
EOF
)

# Replace the version line and the marked asset block in place.
awk -v ver="$ver" -v block="$block" '
  /^  version = "/ { print "  version = \"" ver "\";"; next }
  /BEGIN generated by update-clawpatrol.sh/ { print; print block; skip=1; next }
  /END generated by update-clawpatrol.sh/   { skip=0 }
  skip { next }
  { print }
' "$overlay" > "$overlay.tmp" && mv "$overlay.tmp" "$overlay"

echo "Updated $overlay to clawpatrol v$ver"
