# clawpatrol — "Security firewall for agents" (https://clawpatrol.dev)
#
# Method A packaging: wrap the prebuilt release binary from GitHub Releases
# rather than building from source. clawpatrol is a Go binary (statically
# linked on Linux, so no autoPatchelf needed) with a Deno-built dashboard
# embedded at compile time, so the upstream release artifact is self-contained.
#
# Updating: run ./update-clawpatrol.sh <version> at the repo root, which pulls
# the published SHA256SUMS asset and regenerates the `version` + `asset` block
# below. The hashes here are the file-content hashes that fetchurl verifies,
# identical to the values in the release's SHA256SUMS (just SRI-encoded).
final: prev:
let
  version = "0.5.8";
  inherit (final.stdenv.hostPlatform) system;

  # --- BEGIN generated by update-clawpatrol.sh ---
  binAssets = {
    "x86_64-linux"   = { name = "clawpatrol-linux-amd64";  hash = "sha256-DTFx7UQTw+24xbPHd50m+nogdPnNNrywpiWn/6JE/tc="; };
    "aarch64-linux"  = { name = "clawpatrol-linux-arm64";  hash = "sha256-OVkloi45+zvZdJmGIjqKXZrFBHo6xDHGl0ccsFUysqM="; };
    "x86_64-darwin"  = { name = "clawpatrol-darwin-amd64"; hash = "sha256-UpvsScZ6l12aL90BiER3HfuYl9tQS8mI/AQk6aw4N84="; };
    "aarch64-darwin" = { name = "clawpatrol-darwin-arm64"; hash = "sha256-m0fp24ifocs170nVNNOzptOlcamK48MFwmRc3MrHYgY="; };
  };
  # macOS .app bundle (same artifact for both darwin arches in the release).
  appHash = "sha256-U9mbQUcURxlSsaflWgxw/iKfMgy47a+i65nuVKqqmK4=";
  # --- END generated by update-clawpatrol.sh ---

  asset = binAssets.${system} or (throw "clawpatrol: unsupported system ${system}");
in
{
  clawpatrol = final.stdenvNoCC.mkDerivation {
    pname = "clawpatrol";
    inherit version;

    src = final.fetchurl {
      url = "https://github.com/denoland/clawpatrol/releases/download/v${version}/${asset.name}";
      inherit (asset) hash;
    };

    dontUnpack = true; # src is a single binary, not an archive

    installPhase = ''
      runHook preInstall
      install -Dm755 $src $out/bin/clawpatrol
      runHook postInstall
    '';

    meta = with final.lib; {
      description = "Security firewall for agents";
      homepage = "https://clawpatrol.dev";
      license = licenses.mit;
      mainProgram = "clawpatrol";
      platforms = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      sourceProvenance = [ sourceTypes.binaryNativeCode ];
    };
  };

  # macOS .app bundle that ships the system extension `clawpatrol run` needs.
  # We only *stage* it in the store here; placing it into /Applications (where
  # macOS validates and activates the system extension from a real, non-symlink
  # bundle) is done imperatively by a home.activation step in home.nix — mirror
  # of what install.sh does. Linux just gets a clear throw.
  clawpatrol-app =
    if !final.stdenv.hostPlatform.isDarwin then
      throw "clawpatrol-app is only available on macOS"
    else
      final.stdenvNoCC.mkDerivation {
        pname = "clawpatrol-app";
        inherit version;

        src = final.fetchurl {
          url = "https://github.com/denoland/clawpatrol/releases/download/v${version}/Clawpatrol.app.tar.gz";
          hash = appHash;
        };

        # Tarball root contains Clawpatrol.app/; keep it intact (don't let
        # stdenv cd into the bundle) and preserve the code signature.
        sourceRoot = ".";
        dontConfigure = true;
        dontBuild = true;
        dontFixup = true; # never rewrite/strip a signed .app — it invalidates the signature

        installPhase = ''
          runHook preInstall
          mkdir -p "$out/Applications"
          cp -R Clawpatrol.app "$out/Applications/Clawpatrol.app"
          runHook postInstall
        '';

        meta = with final.lib; {
          description = "Clawpatrol.app — macOS system extension host for clawpatrol";
          homepage = "https://clawpatrol.dev";
          license = licenses.mit;
          platforms = [ "x86_64-darwin" "aarch64-darwin" ];
          sourceProvenance = [ sourceTypes.binaryNativeCode ];
        };
      };
}
