# clawpatrol — "Security firewall for agents" (https://clawpatrol.dev)
#
# Method A packaging: wrap the prebuilt release binary from GitHub Releases
# rather than building from source. clawpatrol is a Go binary (statically
# linked on Linux, so no autoPatchelf needed) with a Deno-built dashboard
# embedded at compile time, so the upstream release artifact is self-contained.
#
# Updating: run ./update-clawpatrol.sh <version> at the repo root, which pulls
# the published SHA256SUMS asset and regenerates the `version` + `asset` block
# below. The hashes here are the file-content hashes that fetchurl verifies,
# identical to the values in the release's SHA256SUMS (just SRI-encoded).
final: prev:
let
  version = "0.5.2";
  inherit (final.stdenv.hostPlatform) system;

  # --- BEGIN generated by update-clawpatrol.sh ---
  asset = {
    "x86_64-linux"   = { name = "clawpatrol-linux-amd64";  hash = "sha256-6DmaFKtQdU9WT3gSF/RNATTI8Crr6CGmntKW2fKKWuY="; };
    "aarch64-linux"  = { name = "clawpatrol-linux-arm64";  hash = "sha256-RdR4zBqgAtBoyziwWGH4wjkW2dZZRo6yW6azwW8Cb70="; };
    "x86_64-darwin"  = { name = "clawpatrol-darwin-amd64"; hash = "sha256-EUWulIaDPZIJkN2xUAkGyuXL4BdL8IyMRq7d24Udw0Q="; };
    "aarch64-darwin" = { name = "clawpatrol-darwin-arm64"; hash = "sha256-IUXOM0EUGTN3QHRRwe6TmIudjtBEZP//cZ7Ja6wjR2A="; };
  }.${system} or (throw "clawpatrol: unsupported system ${system}");
  # --- END generated by update-clawpatrol.sh ---
in
{
  clawpatrol = final.stdenvNoCC.mkDerivation {
    pname = "clawpatrol";
    inherit version;

    src = final.fetchurl {
      url = "https://github.com/denoland/clawpatrol/releases/download/v${version}/${asset.name}";
      inherit (asset) hash;
    };

    dontUnpack = true; # src is a single binary, not an archive

    installPhase = ''
      runHook preInstall
      install -Dm755 $src $out/bin/clawpatrol
      runHook postInstall
    '';

    meta = with final.lib; {
      description = "Security firewall for agents";
      homepage = "https://clawpatrol.dev";
      license = licenses.mit;
      mainProgram = "clawpatrol";
      platforms = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      sourceProvenance = [ sourceTypes.binaryNativeCode ];
    };
  };
}
